packaging_format = 2

id = "minecraft"
name = "Minecraft"
description.en = "Three-dimensional sandbox construction game"
description.fr = "Jeu de construction de type \"bac à sable\" en trois dimensions"

version = "1.24.0~ynh1"

maintainers = []

[upstream]
license = "non-free"
website = "https://www.minecraft.net/"
admindoc = "https://minecraft.fandom.com/wiki/Tutorials/Setting_up_a_server"

[integration]
yunohost = ">= 12.1.25"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.server]
    ask.en = "Select your server"
    ask.fr = "Choisir votre serveur"
    type = "select"
    choices = ["vanilla", "paper", "fabric"]
    default = "vanilla"

    [install.ram]
    ask.en = "Set the memory limit for the server. Convert the number to mebibytes (binary MB): for example, 2GB = 2048, 4GB = 4096..."
    ask.fr = "Définir la mémoire du serveur ? Convertir le chiffre en mébioctets (Mo binaires) : soit 2Go = 2048, 4Go = 4096..."
    type = "select"
    choices = ["1024","2048","4096","6144","8096","8192","10240","12288","16384"]
    default = "2048"

    [install.op]
    ask.en = "Enter the administrator name (Minecraft pseudo)"
    ask.fr = "Entrer le nom de l'adminsitrateur (pseudo Minecraft)"
    type = "string"

    [install.password]
    help.en = "Enter the RCON password"
    help.fr = "Entrer le mot de passe RCON"
    type = "password"

[resources]
    [resources.sources]
#        [resources.sources.mcrcon]
#        url = "https://github.com/Tiiffi/mcrcon/releases/download/v0.7.2/mcrcon-0.7.2-linux-x86-64-static.zip"
#        sha256 = "790bfdd4f51245bc40f909e3a915f98cf569f57b0edf47697f5d72e0b86c2877"
#        in_subdir = false

        [resources.sources.fabric]
	url = "https://meta.fabricmc.net/v2/versions/loader/1.21.10/0.17.3/1.1.0/server/jar"
        sha256 = "373d2dac676afea5091a478b83bbf6db6599d9be4abd90f38d2ed6f93d8fba35"
        rename = "server.jar"
        in_subdir = false
        extract = false

        [resources.sources.paper]
	url = "https://fill-data.papermc.io/v1/objects/8de7c52c3b02403503d16fac58003f1efef7dd7a0256786843927fa92ee57f1e/paper-1.21.8-60.jar"
        sha256 = "8de7c52c3b02403503d16fac58003f1efef7dd7a0256786843927fa92ee57f1e"
        rename = "server.jar"
        in_subdir = false
        extract = false

        [resources.sources.vanilla]
        url = "https://piston-data.mojang.com/v1/objects/45810d238246d90e811d896f87b14695b7fb6839/server.jar"
        sha256 = "e153b89b02c0839cdf5e8c1d57c80dd42a3fffb80c60817632080c041bf8afb5"
        rename = "server.jar"
        in_subdir = false
        extract = false
        

    [resources.ports]
    main.default = 25565
    main.exposed = "TCP"
    rconport.default = 25575
    rconport.exposed = "TCP"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]

#    [resources.apt]
#    packages = "openjdk-21-jre"

    # [resources.apt]
    # packages_from_raw_bash = """
    # debian=$(lsb_release --codename --short)
    # if [[ $debian = "bullseye" ]]; then
    #     echo "openjdk-11-jre";
    # elif [[ $debian = "bookworm" ]]; then
    #     echo "openjdk-17-jre";
    # fi
    # """
